/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Cheap probe for orchestration (systemd, k8s, docker healthcheck). Touches no state.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/radios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List attached radios
         * @description Returns every radio currently registered with the daemon — radio_id, identity, connection status. Clients use this to populate a radio picker before drilling into per-radio resources.
         */
        get: operations["list-radios"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/radios/{radio_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Per-radio session snapshot
         * @description Identity, telemetry, current channel, connection status for one radio. Useful for clients rendering a status bar.
         */
        get: operations["get-radio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/radios/{radio_id}/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List configured channel slots for one radio
         * @description Returns the radio's channel table — name, role, slot index, has-PSK flag. PSK bytes are NEVER emitted by this endpoint; they stay on the daemon side.
         */
        get: operations["list-channels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/radios/{radio_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-sent events stream for one radio
         * @description Live SSE stream of mesh activity for the named radio — text packets, node-info beacons, channel changes, position fixes, routing acks, traceroute / ping replies. Clients consume this for real-time UI updates.
         */
        get: operations["events-stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/radios/{radio_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List chat messages for one radio
         * @description Returns persisted + live in-memory chat rows in chronological order. Optional ?limit= caps response to the most recent N rows.
         */
        get: operations["list-messages"];
        put?: never;
        /**
         * Send a chat message via one radio
         * @description Enqueues an outbound text message on the named channel. Returns the allocated MeshPacket.id; clients correlate this with subsequent ack / fail events from the SSE stream.
         */
        post: operations["send-message"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/radios/{radio_id}/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List known mesh peers for one radio
         * @description Returns every peer the radio's NodeDB has seen, with the most-recent telemetry (SNR, RSSI, hops) and derived state (online / offline / muted).
         */
        get: operations["list-nodes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transports/ble/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List paired Bluetooth devices
         * @description Returns every BLE device the daemon has saved for auto-connect. Favorite devices are flagged.
         */
        get: operations["list-ble-devices"];
        put?: never;
        /**
         * Pair a Bluetooth radio
         * @description Opens an encrypted GATT connection to trigger OS-level bonding (PIN prompt on macOS, agent on Linux), then saves the device to the daemon's pairing table.
         */
        post: operations["pair-ble"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transports/ble/devices/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a paired Bluetooth device
         * @description Removes the device from the saved-pairings table. Does not unbind at the OS level.
         */
        delete: operations["forget-ble-device"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transports/ble/devices/{uuid}/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Mark a Bluetooth device as the auto-connect favorite
         * @description Sets this device as the bare-`meshx` auto-connect target when no USB radio is plugged in.
         */
        put: operations["set-ble-favorite"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transports/ble/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Clear the auto-connect favorite
         * @description Removes the favorite flag from whichever device currently holds it. Auto-connect falls back to the single-saved-device rule.
         */
        delete: operations["clear-ble-favorite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transports/ble/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scan for nearby Meshtastic radios over Bluetooth
         * @description Runs a discovery scan for the configured timeout (default 10s) and returns peripherals advertising the Meshtastic GATT service.
         */
        post: operations["scan-ble"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transports/usb/auto": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Auto-detect a single Meshtastic radio on USB
         * @description Convenience over /transports/usb/scan — returns the device path of the single Meshtastic radio found. 404 when zero, 409 when multiple.
         */
        post: operations["auto-detect-usb"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/transports/usb/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Identify Meshtastic radios on USB-serial
         * @description Walks every candidate USB-serial port, sends a Meshtastic WantConfigId handshake, returns each port's outcome (IsMeshtastic + node identity, or a reason it didn't respond).
         */
        post: operations["scan-usb"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AutoUSBInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/AutoUSBInputBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description per-port identify timeout in milliseconds; default 1500
             */
            timeout_ms?: number;
        };
        AutoUSBOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/AutoUSBOutputBody.json
             */
            readonly $schema?: string;
            /** @description serial device path of the single Meshtastic radio found */
            port: string;
        };
        BLEDeviceView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/BLEDeviceView.json
             */
            readonly $schema?: string;
            favorite: boolean;
            hw_model?: string;
            long_name?: string;
            short_name?: string;
            uuid: string;
        };
        BLESighting: {
            /** @description name advertised by the radio; empty when unset */
            local_name: string;
            /**
             * Format: int32
             * @description signal strength in dBm; closer to zero = stronger
             */
            rssi: number;
            /** @description peripheral identifier — pass to /transports/ble/devices to pair */
            uuid: string;
        };
        ChannelInfo: {
            HasPSK: boolean;
            /** Format: int32 */
            ID: number;
            /** Format: int64 */
            Index: number;
            Name: string;
            PSK: string;
            Role: string;
        };
        ChannelItem: {
            /** @description true when this slot is encrypted (computed from PSK presence) */
            has_psk: boolean;
            /**
             * Format: int64
             * @description radio slot 0..7
             */
            index: number;
            /** @description channel display name; empty for the unnamed primary */
            name: string;
            /** @description true when the channel uses a non-default PSK */
            private: boolean;
            /** @description PRIMARY | SECONDARY | DISABLED */
            role: string;
            /**
             * Format: int64
             * @description unread message count for the tab badge
             */
            unread: number;
        };
        ConfigComplete: Record<string, never>;
        DeviceConfig: {
            Role: string;
        };
        DeviceMetrics: {
            /** Format: float */
            AirUtilTx: number;
            /** Format: int64 */
            BatteryLevel: number;
            /** Format: float */
            ChannelUtil: number;
            /** Format: int64 */
            FromNodeNum: number;
            /** Format: float */
            Voltage: number;
        };
        Disconnected: Record<string, never>;
        EnvMetrics: {
            /** Format: int64 */
            FromNodeNum: number;
            /** Format: float */
            Gas: number;
            /** Format: float */
            Humidity: number;
            /** Format: float */
            Pressure: number;
            /** Format: float */
            Temperature: number;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        HealthOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HealthOutputBody.json
             */
            readonly $schema?: string;
            /** @description always 'ok' when the server is responsive */
            status: string;
        };
        ListBLEDevicesOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListBLEDevicesOutputBody.json
             */
            readonly $schema?: string;
            devices: components["schemas"]["BLEDeviceView"][] | null;
        };
        ListChannelsOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListChannelsOutputBody.json
             */
            readonly $schema?: string;
            channels: components["schemas"]["ChannelItem"][] | null;
        };
        ListMessagesOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListMessagesOutputBody.json
             */
            readonly $schema?: string;
            messages: components["schemas"]["MessageItem"][] | null;
        };
        ListNodesOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListNodesOutputBody.json
             */
            readonly $schema?: string;
            nodes: components["schemas"]["NodeItem"][] | null;
        };
        ListRadiosOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListRadiosOutputBody.json
             */
            readonly $schema?: string;
            radios: components["schemas"]["RadioSummary"][] | null;
        };
        LoraConfig: {
            ModemPreset: string;
            Region: string;
            /** Format: int32 */
            TxPowerDBm: number;
        };
        Message: {
            /** @description leading verb for ham-bang messages */
            bang?: string;
            /** @description sanitization replaced/dropped bytes */
            corrupted?: boolean;
            /** @description sender callsign at receive time */
            from: string;
            /**
             * Format: int64
             * @description sender node num
             */
            from_num: number;
            /**
             * Format: int64
             * @description mesh hop count; 0 = direct
             */
            hops: number;
            /** @description true when local user composed this row */
            mine: boolean;
            /**
             * Format: int64
             * @description MeshPacket.id; 0 for system / demo rows
             */
            packet_id: number;
            /**
             * Format: int64
             * @description PacketID this message answers
             */
            reply_id?: number;
            /**
             * Format: date-time
             * @description absolute time of receive / persist
             */
            sent_at: string;
            /** @description signal-to-noise ratio at receive */
            snr?: string;
            /**
             * @description row delivery state. (empty) = inbound chat (no delivery indicator). 'ack' = local radio confirmed transmission — fires within ~1s of send for both broadcasts and DMs (the everyday 'did it leave my radio?' signal). 'pending' = queued locally, ack not yet received. 'fail' = radio rejected the send or the ack timed out. 'system' / 'notice' = synthetic rows the TUI generates for status banners; never persisted to SQLite. For per-peer mesh acks (DMs only), see the 'acks' field.
             * @enum {string}
             */
            status: "" | "ack" | "pending" | "fail" | "system" | "notice";
            /** @description message body, post-sanitization */
            text: string;
            /** @description display timestamp like '09:47' */
            time: string;
            /**
             * Format: int64
             * @description addressee node num; 0xFFFFFFFF = broadcast
             */
            to_num: number;
        };
        MessageItem: {
            /** @description per-peer mesh-relay ack roll-up rendered as '↳ N acks — call1 (1h), call2 (2h)' under outgoing messages. POPULATES FOR DMs ONLY — Meshtastic peers generate Routing replies for unicasts (MeshPacket.to=peer.NodeNum) but not for broadcasts (to=0xFFFFFFFF), so this field stays empty for channel messages even after delivery. The local-radio confirmation is on the 'status' field, which flips to 'ack' for both broadcasts and DMs once the radio sends the packet. */
            acks?: string;
            /** @description leading verb for ham-bang messages */
            bang?: string;
            /** @description sanitization replaced/dropped bytes */
            corrupted?: boolean;
            /** @description sender callsign at receive time */
            from: string;
            /**
             * Format: int64
             * @description sender node num
             */
            from_num: number;
            /**
             * Format: int64
             * @description mesh hop count; 0 = direct
             */
            hops: number;
            /** @description true when local user composed this row */
            mine: boolean;
            /**
             * Format: int64
             * @description MeshPacket.id; 0 for system / demo rows
             */
            packet_id: number;
            /**
             * Format: int64
             * @description PacketID this message answers
             */
            reply_id?: number;
            /**
             * Format: date-time
             * @description absolute time of receive / persist
             */
            sent_at: string;
            /** @description signal-to-noise ratio at receive */
            snr?: string;
            /**
             * @description row delivery state. (empty) = inbound chat (no delivery indicator). 'ack' = local radio confirmed transmission — fires within ~1s of send for both broadcasts and DMs (the everyday 'did it leave my radio?' signal). 'pending' = queued locally, ack not yet received. 'fail' = radio rejected the send or the ack timed out. 'system' / 'notice' = synthetic rows the TUI generates for status banners; never persisted to SQLite. For per-peer mesh acks (DMs only), see the 'acks' field.
             * @enum {string}
             */
            status: "" | "ack" | "pending" | "fail" | "system" | "notice";
            /** @description message body, post-sanitization */
            text: string;
            /** @description display timestamp like '09:47' */
            time: string;
            /**
             * Format: int64
             * @description addressee node num; 0xFFFFFFFF = broadcast
             */
            to_num: number;
        };
        Metadata: {
            /** Format: int64 */
            DeviceStateVer: number;
            FirmwareVersion: string;
            HasBluetooth: boolean;
            HasWifi: boolean;
        };
        MyInfo: {
            /** Format: int64 */
            NodeNum: number;
        };
        NodeInfo: {
            /** Format: int64 */
            Hops: number;
            HwModel: string;
            /** Format: date-time */
            LastHeardAt: string;
            LongName: string;
            /** Format: int64 */
            NodeNum: number;
            RSSI: string;
            SNR: string;
            ShortName: string;
        };
        NodeItem: {
            /** @description long-form callsign as set on the radio */
            callsign: string;
            /** @description user marked this peer with * */
            fav: boolean;
            /** @description firmware version string */
            firmware: string;
            /**
             * Format: int64
             * @description sort stability — lower = more recent
             */
            heard_rank: number;
            /** @description e.g. T-Beam v1.1, HELTEC_V3 */
            hw_model: string;
            /** @description display string ('2m', '14:02', '3h') */
            last_heard: string;
            /**
             * Format: date-time
             * @description absolute time of last decoded packet
             */
            last_heard_at: string;
            /**
             * Format: int64
             * @description hop count of last received packet (0 = direct)
             */
            last_hops: number;
            /** @description most recent RSSI (dBm), e.g. -92 */
            last_rssi: string;
            /** @description most recent SNR (dB), e.g. -8.5 */
            last_snr: string;
            /**
             * Format: int64
             * @description radio identity, derived from MAC
             */
            node_num: number;
            /** @description 4-char badge */
            short_name: string;
            /** @description online | offline | failed | muted | (empty for unknown) */
            state: string;
            /** @description identity is a synthesized placeholder; no NodeInfo yet */
            unresolved: boolean;
        };
        PairBLEInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PairBLEInputBody.json
             */
            readonly $schema?: string;
            /** @description peripheral identifier from a /transports/ble/scan result */
            uuid: string;
        };
        Ping: {
            /** Format: date-time */
            At: string;
            /** Format: int64 */
            FromNum: number;
            /** Format: int64 */
            Hops: number;
            RSSI: string;
            /** Format: int64 */
            RequestID: number;
            SNR: string;
        };
        Position: {
            /** Format: int32 */
            Altitude: number;
            /** Format: date-time */
            At: string;
            /** Format: int64 */
            FromNodeNum: number;
            /** Format: double */
            Latitude: number;
            /** Format: double */
            Longitude: number;
        };
        RadioSummary: {
            /** @description transport target string (/dev/cu.*, host:port, ble:<uuid>) */
            connect_dest: string;
            /** @description true once ConfigComplete has fired */
            connected: boolean;
            /**
             * Format: int32
             * @description radio's own node num; zero before MyInfo arrives
             */
            my_node_num: number;
            /** @description canonical radio identifier — 0x<hex node_num> post-handshake, pending:<transport>:<addr> beforehand */
            radio_id: string;
        };
        Reconnecting: {
            /** Format: int64 */
            After: number;
            /** Format: int64 */
            Attempt: number;
            Err: unknown;
        };
        Routing: {
            ErrorName: string;
            /** Format: int64 */
            FromNum: number;
            /** Format: int64 */
            Hops: number;
            OK: boolean;
            Reason: string;
            /** Format: int64 */
            RequestID: number;
        };
        ScanBLEInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ScanBLEInputBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description scan duration in milliseconds; default 10000
             */
            timeout_ms?: number;
        };
        ScanBLEOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ScanBLEOutputBody.json
             */
            readonly $schema?: string;
            devices: components["schemas"]["BLESighting"][] | null;
        };
        ScanUSBInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ScanUSBInputBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description per-port identify timeout in milliseconds; default 1500
             */
            timeout_ms?: number;
        };
        ScanUSBOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ScanUSBOutputBody.json
             */
            readonly $schema?: string;
            devices: components["schemas"]["USBSighting"][] | null;
        };
        SendMessageRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SendMessageRequest.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description target channel slot index (0..7); the current channel's slot is the default
             */
            channel: number;
            /**
             * Format: int32
             * @description PacketID this message replies to
             */
            reply_id?: number;
            /** @description message body */
            text: string;
        };
        SendMessageResult: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SendMessageResult.json
             */
            readonly $schema?: string;
            /** @description false when the pump's outbound buffer was full or no radio is attached */
            ok: boolean;
            /**
             * Format: int32
             * @description MeshPacket.id allocated by the radio (zero if pump rejected the send)
             */
            packet_id: number;
        };
        SessionSnapshot: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SessionSnapshot.json
             */
            readonly $schema?: string;
            /** Format: float */
            air_util_tx?: number;
            /** Format: int32 */
            battery_level?: number;
            /** Format: float */
            battery_voltage?: number;
            /** Format: float */
            channel_util?: number;
            connect_dest: string;
            connected: boolean;
            current_channel: string;
            /** Format: int32 */
            my_altitude?: number;
            my_grid?: string;
            /** Format: double */
            my_latitude?: number;
            /** Format: double */
            my_longitude?: number;
            /** Format: int32 */
            my_node_num: number;
            radio_firmware?: string;
            radio_id: string;
            radio_modem?: string;
            radio_region?: string;
            radio_role?: string;
        };
        Text: {
            Body: components["schemas"]["Message"];
            /** Format: int64 */
            Channel: number;
            RSSI: string;
            /** Format: int64 */
            ToNum: number;
        };
        Traceroute: {
            /** Format: date-time */
            At: string;
            /** Format: int64 */
            FromNum: number;
            /** Format: int64 */
            RequestID: number;
            Route: number[] | null;
            /** Format: int64 */
            ToNum: number;
        };
        TransportError: {
            Err: unknown;
        };
        USBSighting: {
            /** @description e.g. T-Beam v1.1, HELTEC_V3 */
            hw_model?: string;
            /** @description true when the port responded to a Meshtastic WantConfigId handshake */
            is_meshtastic: boolean;
            long_name?: string;
            /** Format: int32 */
            node_num?: number;
            /** @description serial device path (/dev/cu.usbmodem*, /dev/ttyUSB*) */
            port: string;
            /** @description why identification failed; empty when IsMeshtastic */
            reason?: string;
            short_name?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-radios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRadiosOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-radio": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description canonical radio identifier — see GET /radios */
                radio_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionSnapshot"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-channels": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description canonical radio identifier — see GET /radios */
                radio_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListChannelsOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "events-stream": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description canonical radio identifier — see GET /radios */
                radio_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": ({
                        data: components["schemas"]["ChannelInfo"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "channel_info";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["ConfigComplete"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "config_complete";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["DeviceConfig"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "device_config";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["DeviceMetrics"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "device_metrics";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["Disconnected"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "disconnected";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["EnvMetrics"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "env_metrics";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["LoraConfig"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "lora_config";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["Metadata"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "metadata";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["MyInfo"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "my_info";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["NodeInfo"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "node_info";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["Ping"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "ping";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["Position"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "position";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["Reconnecting"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "reconnecting";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["Routing"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "routing";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["Text"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "text";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["Traceroute"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "traceroute";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    } | {
                        data: components["schemas"]["TransportError"];
                        /**
                         * @description The event name.
                         * @constant
                         */
                        event: "transport_error";
                        /** @description The event ID. */
                        id?: number;
                        /** @description The retry time in milliseconds. */
                        retry?: number;
                    })[];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-messages": {
        parameters: {
            query?: {
                /** @description max rows to return; 0 = no limit */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description canonical radio identifier — see GET /radios */
                radio_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListMessagesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "send-message": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description canonical radio identifier — see GET /radios */
                radio_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SendMessageResult"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-nodes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description canonical radio identifier — see GET /radios */
                radio_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListNodesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-ble-devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListBLEDevicesOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "pair-ble": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairBLEInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BLEDeviceView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "forget-ble-device": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description peripheral identifier or saved long/short name */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "set-ble-favorite": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description peripheral identifier or saved long/short name */
                uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BLEDeviceView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "clear-ble-favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "scan-ble": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanBLEInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanBLEOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "auto-detect-usb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AutoUSBInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutoUSBOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "scan-usb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanUSBInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanUSBOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
